### PR TITLE
Aar consumption dex

### PR DESCRIPTION
**Pull request by ialbors**
Update to master and ¿fixed dex problem?

### CODE REVIEW

**Comment by Shusshu** [comment]
Didn't see this until now, Will test.

**Comment by Shusshu** [comment]
It works well

Thx man !! pitty you didn't push it to the official project instead ;) I will do it and put the credit on you !

**Comment by ialbors** [comment]
Thanks for the credit :-)

Anyway, it's still not working properly. I've seen that gradle does some kind of merging with the R.java's, including the one created from the R.txt in the aar. It seems the android plugin leaves this R.java as is omiting this step .

**Comment by Shusshu** [comment]
Ok will have to check it out but it is definitely doing something with the
r. Txt

**Comment by Shusshu** [comment]
It's weird, I think it works well.

Could you point me where you think the problem is?

**Comment by ialbors** [comment]
Let me check it again and I'll let you know.

Thanks!

**Comment by ialbors** [comment]
Hi!

I've created this sample project (with gridlayout-v7.aar and actionbarsherlock as apklib):

https://github.com/ialbors/android-m-p_aar_testproject

> mvn clean package
> grep 0x7f030000 -r target/ 

target/generated-sources/r/android/support/v7/gridlayout/R.java: 
  public static final int default_gap=0x7f030000;     

target/generated-sources/r/com/actionbarsherlock/R.java:
 public static int abs__action_bar_home=0x7f030000;

target/generated-sources/r/test/R.java:
 public static final int abs__action_bar_home=0x7f030000;  

They all have the same id (0x7f030000) but they are different attributes.

**Comment by ialbors** [comment]
Well, two of them are the same attribute but the aar's one is different.

**Comment by Shusshu** [comment]
Can you also push the build.gradle ?

Benoit Billington

**Comment by Shusshu** [comment]
Oh okay there's an apklib and an aar.

Benoit Billington

**Comment by Shusshu** [comment]
let's continue the talk in issue #2

**Pull request merged**
